### Sintaxe básica

Existem diversos métodos que podem ser usados para inicializar um array, os mais comuns são:

* **Array{type}(dim...)** - gera arrays densamente povoados
* **zeros(type,dim...)** - gera arrays populados com zeros, por padrão eles sendo Float64
* **ones** - quase igual ao *zeros* mas com o array sendo populado por uns
* **rand()** - um de seus métodos é gerar arrays com valores aleatórios entre zero e um


In [1]:
# teste abaixo os métodos descritos acima
arr = rand(3,3,3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 0.953164  0.349105  0.0403639
 0.114787  0.856846  0.959482 
 0.666623  0.627034  0.561314 

[:, :, 2] =
 0.34358    0.393965  0.32713 
 0.681832   0.733358  0.825806
 0.0362636  0.28776   0.865607

[:, :, 3] =
 0.97733    0.242573  0.928049
 0.262757   0.687758  0.979957
 0.0785208  0.235146  0.4478  

#### Outros métodos importantes

* **linspace** - gera um array de valores uniforme
* **reshape** - modifica as dimensões de um array
* **transpose** - rotaciona o array

In [2]:
arr2 = reshape(1:9,3,3)

3×3 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1  4  7
 2  5  8
 3  6  9

In [3]:
arr3 = transpose(arr2)

3×3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

### Algumas operações

Os arrays de Julia contém uma série de características que auxiliam o programador a fazer alguma operação matemática, em geral a sintaxe é similar a Octave e Matlab,incluindo as operações de álgebra linear

In [4]:
# multiplicação de matrizes
arr2 * arr3

3×3 Array{Int64,2}:
 66   78   90
 78   93  108
 90  108  126

In [5]:
# multiplicação de cada valor pelo contido no índice correspondente
arr2 .* arr3

3×3 Array{Int64,2}:
  1   8  21
  8  25  48
 21  48  81

### Acessando os índices

Julia tem algo incomum em relação a maioria das linguagens que é o fato dos índices começarem com valor *1* e não *0* como programadores normalmente estão acostumados e ainda que tenha características circulares como as listas de python, o último elemento é acessado através **end** e não *-1*, isto se deve ao público alvo da linguagem e no seu esforço e aproximação com o modo de trabalhar de matemáticos e físicos.

Outro ponto a considerar é a *"dupla natureza"* dos índices nas matrizes, podemos tratar cada elemento sequencialmente ou através da linha e da coluna

In [6]:
# a vírgula separa a linha da coluna
arr2[1, end]

7

In [7]:
arr2[7]

7

In [8]:
# repare que os índices são considerados verticalmente
arr2

3×3 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1  4  7
 2  5  8
 3  6  9

Ainda sobre os índices de um array, é possível fazer uma série de operações visando filtrar e substituir de alguma forma os valores contidos no array

In [9]:
arr2[arr2.>5]

4-element Array{Int64,1}:
 6
 7
 8
 9

In [11]:
arr2

3×3 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1  4  7
 2  5  8
 3  6  9

In [12]:
indices = [9,1,8,2]
arr2[indices]

4-element Array{Int64,1}:
 9
 1
 8
 2

In [14]:
arr2

3×3 Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}:
 1  4  7
 2  5  8
 3  6  9

uma função interessante sob este aspcto é a **sortperm**

In [15]:
arrDesord = rand(5)

5-element Array{Float64,1}:
 0.13858  
 0.676646 
 0.817603 
 0.0107628
 0.185901 

In [16]:
indicesOrdenados = sortperm(arrDesord)

5-element Array{Int64,1}:
 4
 1
 5
 2
 3

In [17]:
arrDesord[indicesOrdenados]

5-element Array{Float64,1}:
 0.0107628
 0.13858  
 0.185901 
 0.676646 
 0.817603 

### padrão nas funções que manipulam arrays

toda função que terminar com ***!*** modifica o conteúdo do array se aproveitando da passagem por referência, quando não há ***!*** ao final da função, ela devolve um outro array como resultado da operação

In [18]:
# ordena o array original
sort!(arrDesord)

5-element Array{Float64,1}:
 0.0107628
 0.13858  
 0.185901 
 0.676646 
 0.817603 

In [19]:
arrDesord

5-element Array{Float64,1}:
 0.0107628
 0.13858  
 0.185901 
 0.676646 
 0.817603 

In [20]:
# devolve uma cópia do array ordenado mas não ordena o original
arrDesord2 = rand(5)
sort(arrDesord)

5-element Array{Float64,1}:
 0.0107628
 0.13858  
 0.185901 
 0.676646 
 0.817603 

In [21]:
arrDesord2

5-element Array{Float64,1}:
 0.26264 
 0.32599 
 0.697131
 0.188292
 0.935645

## Tipos de arrays

devido ao uso em álgebra linear, Julia mantém uma separação entre vetor, matriz e array, ainda que os dois primeiras sejam tipos específicos de arrays

In [31]:
v = Vector(1:10)
typeof(v)

Array{Int64,1}

In [35]:
m = Matrix(5, 5)
for i in 1:length(m); m[i] = rand(1:5); end
typeof(m)

Array{Any,2}

### Alguns métodos úteis:
*obs.: explicações tiradas da ajuda das funções*

* diag - The **k**th diagonal of a matrix, as a vector. Use **diagm** to construct a diagonal matrix.
* kron - Kronecker tensor product of two vectors or two matrices.
* vecdot - compute the Euclidean dot product (the sum of `dot(x[i],y[i]))` as if they were vectors.
