### Sintaxe básica

Existem diversos métodos que podem ser usados para inicializar um array, os mais comuns são:

* **Array{type}(dim...)** - gera arrays densamente povoados
* **zeros(type,dim...)** - gera arrays populados com zeros, por padrão eles sendo Float64
* **ones** - quase igual ao *zeros* mas com o array sendo populado por uns
* **rand()** - um de seus métodos é gerar arrays com valores aleatórios


In [3]:
# teste abaixo os métodos descritos acima
arr = rand(3,3,3)

3x3x3 Array{Float64,3}:
[:, :, 1] =
 0.650333  0.4712    0.185806
 0.466831  0.153602  0.869515
 0.703204  0.586341  0.628053

[:, :, 2] =
 0.325045  0.284242  0.44888 
 0.35724   0.237984  0.999288
 0.623642  0.503044  0.341818

[:, :, 3] =
 0.157519  0.617777  0.13274 
 0.49116   0.49757   0.787842
 0.818809  0.873323  0.634506

#### Outros métodos importantes

* **linspace** - gera um array de valores uniforme
* **reshape** - modifica as dimensões de um array
* **transpose** - rotaciona o array

In [4]:
arr2 = reshape(1:9,3,3)

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [5]:
arr3 = transpose(arr2)

3x3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

### Algumas operações

Os arrays de Julia contém uma série de características que auxiliam o programador a fazer alguma operação matemática, em geral a sintaxe é similar a Octave e Matlab,incluindo as operações de álgebra linear

In [9]:
arr2 * arr3

3x3 Array{Int64,2}:
 66   78   90
 78   93  108
 90  108  126

In [10]:
arr2 .* arr3

3x3 Array{Int64,2}:
  1   8  21
  8  25  48
 21  48  81

### Acessando os índices

Julia tem algo incomum em relação a maioria das linguagens que é o fato dos índices começarem com valor *1* e não *0* como programadores normalmente estão acostumados e ainda que tenha características circulares como as listas de python, o último elemento é acessado através **end** e não *-1*, isto se deve ao público alvo da linguagem e no seu esforço e aproximação com o modo de trabalhar de matemáticos e físicos.

Outro ponto a considerar é a *"dupla natureza"* dos índices nas matrizes, podemos tratar cada elemento sequencialmente ou através da linha e da coluna

In [6]:
# a vírgula separa a linha da coluna
arr2[1, end]

7

In [7]:
arr2[7]

7

In [8]:
arr2

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9