### Sintaxe básica

Existem diversos métodos que podem ser usados para inicializar um array, os mais comuns são:

* **Array{type}(dim...)** - gera arrays densamente povoados
* **zeros(type,dim...)** - gera arrays populados com zeros, por padrão eles sendo Float64
* **ones** - quase igual ao *zeros* mas com o array sendo populado por uns
* **rand()** - um de seus métodos é gerar arrays com valores aleatórios entre zero e um


In [1]:
# teste abaixo os métodos descritos acima
arr = rand(3,3,3)

3x3x3 Array{Float64,3}:
[:, :, 1] =
 0.725341  0.56169    0.290905  
 0.512879  0.716207   0.791666  
 0.230095  0.0421073  0.00638164

[:, :, 2] =
 0.864482  0.874604  0.0889594
 0.930294  0.144321  0.219915 
 0.160723  0.898829  0.434091 

[:, :, 3] =
 0.577095  0.852594   0.527487
 0.973696  0.0321611  0.100549
 0.738842  0.565743   0.315635

#### Outros métodos importantes

* **linspace** - gera um array de valores uniforme
* **reshape** - modifica as dimensões de um array
* **transpose** - rotaciona o array

In [2]:
arr2 = reshape(1:9,3,3)

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

In [3]:
arr3 = transpose(arr2)

3x3 Array{Int64,2}:
 1  2  3
 4  5  6
 7  8  9

### Algumas operações

Os arrays de Julia contém uma série de características que auxiliam o programador a fazer alguma operação matemática, em geral a sintaxe é similar a Octave e Matlab,incluindo as operações de álgebra linear

In [4]:
# multiplicação de matrizes
arr2 * arr3

3x3 Array{Int64,2}:
 66   78   90
 78   93  108
 90  108  126

In [5]:
# multiplicação de cada valor pelo contido no índice correspondente
arr2 .* arr3

3x3 Array{Int64,2}:
  1   8  21
  8  25  48
 21  48  81

### Acessando os índices

Julia tem algo incomum em relação a maioria das linguagens que é o fato dos índices começarem com valor *1* e não *0* como programadores normalmente estão acostumados e ainda que tenha características circulares como as listas de python, o último elemento é acessado através **end** e não *-1*, isto se deve ao público alvo da linguagem e no seu esforço e aproximação com o modo de trabalhar de matemáticos e físicos.

Outro ponto a considerar é a *"dupla natureza"* dos índices nas matrizes, podemos tratar cada elemento sequencialmente ou através da linha e da coluna

In [6]:
# a vírgula separa a linha da coluna
arr2[1, end]

7

In [7]:
arr2[7]

7

In [8]:
# repare que os índices são considerados verticalmente
arr2

3x3 Array{Int64,2}:
 1  4  7
 2  5  8
 3  6  9

Ainda sobre os índices de um array, é possível fazer uma série de operações visando filtrar e substituir de alguma forma os valores contidos no array

In [9]:
arr2[arr2.>5]

4-element Array{Int64,1}:
 6
 7
 8
 9

In [10]:
arr2[arr2.<5] = 999

999

In [11]:
arr2

3x3 Array{Int64,2}:
 999  999  7
 999    5  8
 999    6  9

In [12]:
indices = [9,1,8,2]
arr2[indices]

4-element Array{Int64,1}:
   9
 999
   8
 999

In [13]:
arr2[indices] = 0

0

In [14]:
arr2

3x3 Array{Int64,2}:
   0  999  7
   0    5  0
 999    6  0

uma função interessante sob este aspcto é a **sortperm**

In [15]:
arrDesord = rand(5)

5-element Array{Float64,1}:
 0.780642
 0.387205
 0.204987
 0.907312
 0.33542 

In [16]:
indicesOrdenados = sortperm(arrDesord)

5-element Array{Int64,1}:
 3
 5
 2
 1
 4

In [17]:
arrDesord[indicesOrdenados]

5-element Array{Float64,1}:
 0.204987
 0.33542 
 0.387205
 0.780642
 0.907312

### padrão nas funções que manipulam arrays

toda função que terminar com ***!*** modifica o conteúdo do array se aproveitando da passagem por referência, quando não há ***!*** ao final da função, ela devolve um outro array como resultado da operação

In [18]:
# ordena o array original
sort!(arrDesord)

5-element Array{Float64,1}:
 0.204987
 0.33542 
 0.387205
 0.780642
 0.907312

In [19]:
arrDesord

5-element Array{Float64,1}:
 0.204987
 0.33542 
 0.387205
 0.780642
 0.907312

In [20]:
# devolve uma cópia do array ordenado mas não ordena o original
arrDesord2 = rand(5)
sort(arrDesord)

5-element Array{Float64,1}:
 0.204987
 0.33542 
 0.387205
 0.780642
 0.907312

In [21]:
arrDesord2

5-element Array{Float64,1}:
 0.756484 
 0.778608 
 0.607003 
 0.681206 
 0.0233712